Repository bellshade/PHP, pull requests merged in 2021-10, with the labels that each got.

#30 add: Menambahkan materi pengkondisian
  basics/4_conditional_statements/1_if_elseif_else.php
  basics/4_conditional_statements/2_switch.php
  basics/4_conditional_statements/README.md
  basics/4_conditional_statements/index.php
Labels: enhancement

#35 add: Materi Penanganan Formulir (7_form_handling)
  basics/7_form_handling/1_submit_button.php
  basics/7_form_handling/2_input_based_text.php
  basics/7_form_handling/3_select.php
  basics/7_form_handling/README.md
  basics/7_form_handling/index.php
Labels: documentation, enhancement

#37 docs: menyunting README.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted
